//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteTools.Presentation.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteTools.Presentation.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Gartoon_Team_Gartoon_Apps_Gnome_remote_shell {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_1024 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_128 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_16 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_24 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_256 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_32 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_48 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_512 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gartoon_Team_Gartoon_Apps_Gnome_remote_shell_64 {
            get {
                object obj = ResourceManager.GetObject("Gartoon-Team-Gartoon-Apps-Gnome-remote-shell.64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string GUI_TrayIcon_Exit {
            get {
                return ResourceManager.GetString("GUI_TrayIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string GUI_TrayIcon_Settings {
            get {
                return ResourceManager.GetString("GUI_TrayIcon_Settings", resourceCulture);
            }
        }
    }
}
